//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 09:24:04 PM EEST 
//


package cy.ac.ucy.linc.CloudSoftwareRepo.XML;

import javax.xml.bind.annotation.XmlRegistry;

import cy.ac.ucy.linc.CloudSoftwareRepo.XML.Artifact;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cy.ac.ucy.linc.CloudSoftwareRepo.XML package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ArtifactFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cy.ac.ucy.linc.CloudSoftwareRepo.XML
     * 
     */
    public ArtifactFactory() {
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

}
