//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 08:03:32 PM EEST 
//


package cy.ac.ucy.linc.CloudSoftwareRepo.XML;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cy.ac.ucy.linc.CloudSoftwareRepo.XML package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class StatusFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cy.ac.ucy.linc.CloudSoftwareRepo.XML
     * 
     */
    public StatusFactory() {
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Status.Data }
     * 
     */
    public Status.Data createStatusData() {
        return new Status.Data();
    }

}
