//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 08:03:32 PM EEST 
//


package cy.ac.ucy.linc.CloudSoftwareRepo.XML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="appName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="formattedAppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="apiVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="editionLong" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="editionShort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="attributionsURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="purchaseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="userLicenseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="initializedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="startedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastConfigChange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="instanceUpgraded" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="configurationUpgraded" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="licenseInstalled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="licenseExpired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="trialLicense" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name="", propOrder = {
    "data"
}/*, factoryClass=StatusFactory.class, factoryMethod="createStatus"*/)
@XmlRootElement(name = "status")
public class Status {

    @XmlElement(required = true)
    protected Status.Data data;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Status.Data }
     *     
     */
    public Status.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status.Data }
     *     
     */
    public void setData(Status.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="appName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="formattedAppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="apiVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="editionLong" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="editionShort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="attributionsURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="purchaseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="userLicenseURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="initializedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="startedAt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastConfigChange" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="instanceUpgraded" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="configurationUpgraded" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="baseUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="licenseInstalled" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="licenseExpired" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="trialLicense" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "appName",
        "formattedAppName",
        "version",
        "apiVersion",
        "editionLong",
        "editionShort",
        "attributionsURL",
        "purchaseURL",
        "userLicenseURL",
        "state",
        "initializedAt",
        "startedAt",
        "lastConfigChange",
        "firstStart",
        "instanceUpgraded",
        "configurationUpgraded",
        "baseUrl",
        "licenseInstalled",
        "licenseExpired",
        "trialLicense"
    }/*, factoryClass=StatusFactory.class, factoryMethod="createStatusFactoryData"*/)
    public static class Data {

        @XmlElement(required = true)
        protected String appName;
        @XmlElement(required = true)
        protected String formattedAppName;
        @XmlElement(required = true)
        protected String version;
        @XmlElement(required = true)
        protected String apiVersion;
        @XmlElement(required = true)
        protected String editionLong;
        @XmlElement(required = true)
        protected String editionShort;
        @XmlElement(required = true)
        protected String attributionsURL;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String purchaseURL;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String userLicenseURL;
        @XmlElement(required = true)
        protected String state;
        @XmlElement(required = true)
        protected String initializedAt;
        @XmlElement(required = true)
        protected String startedAt;
        @XmlElement(required = true)
        protected String lastConfigChange;
        @XmlElement(required = true)
        protected String firstStart;
        @XmlElement(required = true)
        protected String instanceUpgraded;
        @XmlElement(required = true)
        protected String configurationUpgraded;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String baseUrl;
        @XmlElement(required = true)
        protected String licenseInstalled;
        @XmlElement(required = true)
        protected String licenseExpired;
        @XmlElement(required = true)
        protected String trialLicense;

        /**
         * Gets the value of the appName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAppName() {
            return appName;
        }

        /**
         * Sets the value of the appName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAppName(String value) {
            this.appName = value;
        }

        /**
         * Gets the value of the formattedAppName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormattedAppName() {
            return formattedAppName;
        }

        /**
         * Sets the value of the formattedAppName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormattedAppName(String value) {
            this.formattedAppName = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the apiVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApiVersion() {
            return apiVersion;
        }

        /**
         * Sets the value of the apiVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApiVersion(String value) {
            this.apiVersion = value;
        }

        /**
         * Gets the value of the editionLong property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEditionLong() {
            return editionLong;
        }

        /**
         * Sets the value of the editionLong property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEditionLong(String value) {
            this.editionLong = value;
        }

        /**
         * Gets the value of the editionShort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEditionShort() {
            return editionShort;
        }

        /**
         * Sets the value of the editionShort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEditionShort(String value) {
            this.editionShort = value;
        }

        /**
         * Gets the value of the attributionsURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttributionsURL() {
            return attributionsURL;
        }

        /**
         * Sets the value of the attributionsURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttributionsURL(String value) {
            this.attributionsURL = value;
        }

        /**
         * Gets the value of the purchaseURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPurchaseURL() {
            return purchaseURL;
        }

        /**
         * Sets the value of the purchaseURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPurchaseURL(String value) {
            this.purchaseURL = value;
        }

        /**
         * Gets the value of the userLicenseURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserLicenseURL() {
            return userLicenseURL;
        }

        /**
         * Sets the value of the userLicenseURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserLicenseURL(String value) {
            this.userLicenseURL = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the initializedAt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInitializedAt() {
            return initializedAt;
        }

        /**
         * Sets the value of the initializedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInitializedAt(String value) {
            this.initializedAt = value;
        }

        /**
         * Gets the value of the startedAt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStartedAt() {
            return startedAt;
        }

        /**
         * Sets the value of the startedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStartedAt(String value) {
            this.startedAt = value;
        }

        /**
         * Gets the value of the lastConfigChange property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastConfigChange() {
            return lastConfigChange;
        }

        /**
         * Sets the value of the lastConfigChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastConfigChange(String value) {
            this.lastConfigChange = value;
        }

        /**
         * Gets the value of the firstStart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstStart() {
            return firstStart;
        }

        /**
         * Sets the value of the firstStart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstStart(String value) {
            this.firstStart = value;
        }

        /**
         * Gets the value of the instanceUpgraded property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInstanceUpgraded() {
            return instanceUpgraded;
        }

        /**
         * Sets the value of the instanceUpgraded property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInstanceUpgraded(String value) {
            this.instanceUpgraded = value;
        }

        /**
         * Gets the value of the configurationUpgraded property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConfigurationUpgraded() {
            return configurationUpgraded;
        }

        /**
         * Sets the value of the configurationUpgraded property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConfigurationUpgraded(String value) {
            this.configurationUpgraded = value;
        }

        /**
         * Gets the value of the baseUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBaseUrl() {
            return baseUrl;
        }

        /**
         * Sets the value of the baseUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBaseUrl(String value) {
            this.baseUrl = value;
        }

        /**
         * Gets the value of the licenseInstalled property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLicenseInstalled() {
            return licenseInstalled;
        }

        /**
         * Sets the value of the licenseInstalled property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLicenseInstalled(String value) {
            this.licenseInstalled = value;
        }

        /**
         * Gets the value of the licenseExpired property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLicenseExpired() {
            return licenseExpired;
        }

        /**
         * Sets the value of the licenseExpired property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLicenseExpired(String value) {
            this.licenseExpired = value;
        }

        /**
         * Gets the value of the trialLicense property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrialLicense() {
            return trialLicense;
        }

        /**
         * Sets the value of the trialLicense property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrialLicense(String value) {
            this.trialLicense = value;
        }

    }

}
